query_metrics:
  in: query
  name: metrics
  required: true
  description: >
    List of analytics to return.
     At least one in that list.
  schema:
    type: string
    enum:
      - business_impressions_desktop_maps
      - business_impressions_desktop_search
      - business_impressions_mobile_maps
      - business_impressions_mobile_search
      - business_direction_requests
      - call_clicks
      - website_clicks

query_dimensions:
  in: query
  name: dimensions
  required: false
  description: |
    How the returned data will be aggregated.
    At most 'business' and one time dimensions of the list.
    If no dimension is given, the request will return the sum of each metric for all requested days and businesses.
  schema:
    type: string
    enum:
      - business
      - day
      - week
      - month
      - year

query_order_by:
  in: query
  name: order_by
  required: false
  description: >
    Where the object is either a dimension or a metric
     and is used in the request. At most one in the list.
     - before a field to order_by DESC, nothing for ASC

  schema:
    type: string
    enum:
      - <object>
      - -<object>
    example: order_by=-call_clicks

query_business__in:
  in: query
  name: business__in
  description: Filter by business ids
  required: false
  schema:
    type: array
    items:
      $ref: "./types.yml#/BusinessID"

query_business__notin:
  in: query
  name: business__notin
  required: false
  description: >
    Filter by all allowed businesses except
     the ones given in `business__notin`
  schema:
    type: array
    items:
      $ref: "./types.yml#/BusinessID"

query_city:
  in: query
  name: city
  required: false
  description: Filter by city
  schema:
    type: string

query_query:
  in: query
  name: query
  required: false
  description: >
    Parameter to fuzzy search businesses on city,
     zipcode and name
  schema:
    type: string

query_filter_date__gte:
  in: query
  name: filter_date__gte
  required: false
  description: |
    Filter by `date`

    Return all the analytics whose `date` >= `given_date`.
  schema:
    type: string
    format: datetime

query_filter_date__lte:
  in: query
  name: filter_date__lte
  description: |
    Filter by `date`.

    Return all the analytics whose `filter_date` <= `given_date`.
  schema:
    type: string
    format: datetime
