
state:
  type: string
  enum: [ 'success','pending' , 'to_configure' ]
  example: success

getPublisherStatesParams:
  - $ref: '../index.yml#/parameters/query_business__in'

  - name: publishers
    in: query
    required: false
    description: List of requested publisher names
    schema:
      type: array
      items:
        type: string
      example: facebook,google_my_business

  - name: states
    in: query
    required: false
    description: List of the requested states
    schema:
      type: array
      items:
        $ref: '#/state'
      example: success,to_configure,pending

  - name: per_page
    in: query
    schema:
      type: integer
      default: 5
      minimum: 1
      maximum: 100
    description: Number of items to return per page. Currently limited to 100.

  - name: page
    in: query
    required: false
    description: Page requested
    schema:
      type: integer
      example: 3

postPublisherErrorsParams:
  - $ref: '../index.yml#/parameters/business_id'
