query_metrics:
  in: query
  name: metrics
  required: true
  description: >
    List of analytics to return.
     At least one in that list.
  schema:
    type: string
    enum:
      - average_rating
      - rating_distribution
      - reviews_count
      - reply_time
      - reply_means
      - average_rating_distribution
      - rank

query_dimensions:
  in: query
  name: dimensions
  required: false
  description: |
    How the returned data will be aggregated.
    If no dimension is given, the request will return the sum of each metric for all requested days and businesses.
  schema:
    type: string
    enum:
      - day
      - week
      - month
      - year
      - business
      - group
      - user
      - tag

query_order_by:
  in: query
  name: order_by
  required: false
  description: >
    See above for the list of all orders available. At most one in the list.
     - `-` before a field to order_by DESC, nothing for ASC

  schema:
    type: string
    example: -average_rating

query_business__in:
  in: query
  name: business__in
  description: Filter by business ids
  required: false
  schema:
    type: array
    items:
      $ref: "./types.yml#/BusinessID"

query_business__notin:
  in: query
  name: business__notin
  required: false
  description: >
    Filter by all allowed businesses except
     the ones given in `business__notin`
  schema:
    type: array
    items:
      $ref: "./types.yml#/BusinessID"

query_groups:
  in: query
  name: groups
  description: Filter by groups ids
  required: false
  schema:
    type: array
    items:
      $ref: "./types.yml#/GroupID"

query_update_date__gte:
  in: query
  name: update_date__gte
  required: false
  description: |
    Restrict the data returned on reviews which `update_date` are after the given date.
  schema:
    type: string
    format: datetime

query_update_date__lte:
  in: query
  name: update_date__lte
  description: |
    Restrict the data returned on reviews which `update_date` are before the given date.
  schema:
    type: string
    format: datetime

query_tags:
  in: query
  name: tags
  description: |
    Restrict the data returned on reviews that have been assigned the specified tags.
  schema:
    type: array
    items:
      $ref: "./types.yml#/TagID"

query_page:
  in: query
  name: page
  required: false
  description: |
    The page number you want to request.
  schema:
    type: integer
    minimum: 1
    default: 1

query_per_page:
  in: query
  name: per_page
  required: false
  description: |
    The maximum number of result items to return in a page.
  schema:
    type: integer
    default: 30
